package de.hftstuttgart.puzzles.controller;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.event.ActionEvent;

public class AuftragFXController {
	@FXML
	private Button abbrechen;

	// Event Listener on Button[#abbrechen].onAction
	@FXML
	public void abbrechen(ActionEvent event) {
		// TODO Autogenerated
		OverviewFXController.getStage().close();
	}
}
