package de.hftstuttgart.puzzles.controller;

import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.scene.control.Button;

public class KundenUebersichtController {

	@FXML
	private Button abbrechen;

	// Event Listener on Button[#abbrechen].onAction
	@FXML
	public void abbrechen(ActionEvent event) {
		// TODO Autogenerated
		OverviewFXController.getStage().close();
	}
}
