package de.hftstuttgart.puzzles.controller;

import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.scene.control.Button;
import javafx.scene.control.PasswordField;
import javafx.scene.control.TextField;

public class LoginController {
	@FXML
	private TextField MitarbeiterIDTextfeld;
	@FXML
	private PasswordField Passwortfeld;
	@FXML
	private Button loginButton;

	// Event Listener on TextField[#MitarbeiterIDTextfeld].onAction
	@FXML
	public void MitarbeiterIDtext(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on PasswordField[#Passwortfeld].onAction
	@FXML
	public void passwort(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#loginButton].onAction
	@FXML
	public void LoginButton(ActionEvent event) {
		// TODO Autogenerated
		MitarbeiterIDTextfeld = new TextField();
		Passwortfeld = new PasswordField();

	}
}
