package de.hftstuttgart.puzzles.controller;

import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.scene.control.Button;
import javafx.scene.control.PasswordField;
import javafx.scene.control.TextField;

public class LoginController {
	@FXML
	private TextField MitarbeiterIDTextfeld;
	@FXML
	private PasswordField Passwortfeld;
	@FXML
	private Button loginButton;

	// Event Listener on Button[#loginButton].onAction
	@FXML
	public void LoginButton(ActionEvent event) {
		// TODO Autogenerated

	}
}
