package de.hftstuttgart.puzzles.controller;

import java.io.IOException;

import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.stage.Stage;

public class OverviewFXController {
	private static Stage stage;
	@FXML
	private Button uebersicht;
	@FXML
	private Button Auftrag;
	@FXML
	private Button Kundenübersicht;
	@FXML
	private Button Details;
	@FXML
	private Button Ausgeliefert;
	@FXML
	private Button Neuausdrucken;
	@FXML
	private Button Löschen;

	private Parent root;

	// Event Listener on Button[#Übersicht].onAction
	@FXML
	public void übersicht(ActionEvent event) {
		// TODO Autogenerated
		System.out.println("übersicht");
	}

	// Event Listener on Button[#Auftrag].onAction
	@FXML
	public void auftrag(ActionEvent event) {
		// TODO Autogenerated
		try {
			root = FXMLLoader.load(getClass().getResource("/de/hftStuttgart/puzzles/view/AuftragFX.fxml"));
			stage = new Stage();
			stage.setTitle("Auftragserstellung");
			stage.setScene(new Scene(root, 600, 400));
			stage.setResizable(false);
			stage.show();
		} catch (IOException e) {
			e.printStackTrace();
		}
	}

	// Event Listener on Button[#Kundenübersicht].onAction
	@FXML
	public void kundenübersicht(ActionEvent event) {
		// TODO Autogenerated
		try {
			root = FXMLLoader.load(getClass().getResource("/de/hftStuttgart/puzzles/view/KundenUebersicht.fxml"));
			stage = new Stage();
			stage.setTitle("Kundenübersicht");
			stage.setScene(new Scene(root, 800, 400));
			stage.setResizable(false);
			stage.show();
		} catch (IOException e) {
			e.printStackTrace();
		}
	}

	// Event Listener on Button[#Details].onAction
	@FXML
	public void details(ActionEvent event) {
		// TODO Autogenerated

	}

	public static void stageL() {
	}

	// Event Listener on Button[#Ausgeliefert].onAction
	@FXML
	public void ausgeliefert(ActionEvent event) {
		// TODO Autogenerated
	}

	// Event Listener on Button[#Neuausdrucken].onAction
	@FXML
	public void neuausdrucken(ActionEvent event) {
		// TODO Autogenerated
	}

	// Event Listener on Button[#Löschen].onAction
	@FXML
	public void löschen(ActionEvent event) {
		// TODO Autogenerated
	}

	public static Stage getStage() {
		return stage;
	}
}
